name: initial-workflow
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: Generate ASCII artwork
      run: |
        sudo apt-get install cowsay -y 
        cowsay -f lion "Lion king" >> Leo.txt