name: initial-workflow
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: Welcome message
      run: |
        echo "My first Github Action Job"
        ls -a
        cat README.md
    - name: Generate ASCII artwork
      run: cowsay -f lion "Lion king" >> Leo.txt