name: initial-workflow
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: Executing Shell script
      run: |
        pwd
        ls -l
        chmod +x script.sh  
        ./script.sh
  second_job:
    needs: first_job
    runs-on: ubuntu-latest
    steps:
    - name: Executing Shell script
      run: cat leo.txt