name: initial-workflow
on:
  push:
    branches:
      - 'main'
    paths:
     - "!.github/workflows/*"
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: Executing Shell script
      run: |
        pwd
        ls -l
        chmod +x script.sh  
        ./script.sh
    - name: Upload file Artifact
      uses: actions/upload-artifact@v4
      with:
          name: my-artifact
          path: leo.txt
  second_job:
    needs: first_job
    runs-on: ubuntu-latest
    steps:
    - name: Upload file Artifact
      uses: actions/download-artifact@v4
      with:
          name: my-artifact

    - name: Executing Shell script
      run: cat leo.txt
